### ISSUE TITLE
SpringBoot中的日期转换

### ISSUE THREAD

**Issue by bfchengnuo** [bfchengnuo/MyRecord#32]
最常用的两个注解： `@DateTimeFormat` 和 `@JsonFormat` 

`@DateTimeFormat` 转换前端 String 类型到后端 Date 类型。

`@JsonFormat` 转换后端 Date 类型到前端 String 类型，如果只用到此注解，加到属性上或者方法上都可以；
如果跟 `@DateTimeFormat` 配合使用，此注解添加到 getter 方法上面，注意加 `timezone="GMT+8"`

示例：
``` java
class Main{
  @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
  private Date updateTime;

  // 一般配合 controller 使用
  public void test(@DateTimeFormat(pattern = "yyyy-MM-dd")Date date){}

  @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss", timezone="GMT+8")
  public Date getUpdateTime() {
    return updateTime;
  }

}
```

**Comment by bfchengnuo** [comment]
补充，SpringBoot 中对 Jackson 的一些使用：

``` yml
spring:
  jackson:
    # 全局格式化标准
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    # 忽略 null 值的输出
    default-property-inclusion: non_null


    # 返回时间戳
    # serialization:
    #  write-dates-as-timestamps: true
```

使用 `@JsonSerialize(using = Date2LongSerializer.class)` 来指定转换规则，例如毫秒转换为秒：
``` java
public class Date2LongSerializer extends JsonSerializer<Date> {
    @Override
    public void serialize(Date date, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException {
        jsonGenerator.writeNumber(date.getTime() / 1000);
    }
}
```
