### ISSUE TITLE
Docker Compose 相关

### ISSUE THREAD

**Issue by bfchengnuo** [bfchengnuo/MyRecord#70]
基本命令说明：

常用操作：

**Comment by bfchengnuo** [comment]
### 如何将端口映射动态传递给 docker-compose up 命令？
在 docker-compose.yml 中使用 `${VAR}`

例如
``` yaml
version: '2'
services:
  apache:
    image: httpd:2.4
    volumes:
      - .:/usr/local/apache2/htdocs/
    ports:
      - ${APP_PORT}:80
```

然后使用环境变量：
```
$ export APP_PORT=8080
$ docker-compose up
```
或内联版本：
```
$ APP_PORT=8080 docker-compose up
```
